### ISSUE TITLE
Simpler dependency-lint.yml file

### ISSUE THREAD

**Issue by kevgo** [charlierudolph/dependency-lint#17]
Some random ideas after reviewing this in one of my projects. Instead of adding so much explanation and type information into the documentation, maybe its better to provide a well documented example file in the documentation and link to that from here? This also makes upgrading this file easier, in case future versions of dependency-lint use more or different options. 

``` yaml
# see https://github.com/charlierudolph/dependency-lint-example for an example

# modules that don't have to be used
allowUnused: []

# files only used in development
devFiles:
  - '{features,spec}/**/*'
  - '**/*_spec.coffee'
  - gulpfile.coffee
  - mycha.coffee

# scripts only used in development
devScripts:
  - build
  - lint
  - publish
  - test

# files to be linted
files: '**/*.coffee'

# don't lint these files
ignoreFilePatterns:
  - 'dist/**/*'
  - 'node_modules/**/*'

# ignore webpack loaders when evaluating requires
# example:
#   require('foo!bar!baz')
# is equivalent to:
#   require('baz')
stripLoaders: false


transpilers:
  - extension: .coffee
    module: coffee-script
```
