### ISSUE TITLE
--auto-correct should not delete dependencies listed in ignoreErrors.unused

### ISSUE THREAD

**Issue by nfriedly** [charlierudolph/dependency-lint#37]
I have several things listed in my `ignoreErrors.unused`:

``` yml
ignoreErrors:
  missing: []
  shouldBeDependency: []
  shouldBeDevDependency: []
  unused:
    # babel plugins
    - babel-plugin-add-module-exports
    - babel-plugin-transform-object-assign
    - babel-preset-es2015
    - babel-preset-react
    - babel-preset-stage-0

    # browserify plugins
    - babelify
    - browserify-global-shim
    - minifyify
    - uglifyify

    # eslint plugins
    - eslint-config-airbnb
    - eslint-plugin-import
    - eslint-plugin-jsx-a11y
    - eslint-plugin-react

    # css dependencies
    - watson-ui-component
```

When I run `dependency-lint` these are ignored as expected. However, when I run `dependency-lint --auto-correct` they are again reported as ignored, but are actually "fixed" (deleted from package.json). This, of course, actually breaks things.
